CREATE TABLE IF NOT EXISTS COMPANY_STAFF (
    USER_ID NUMBER(19,0),
    FIRST_NAME VARCHAR2(255 CHAR),
    LAST_NAME VARCHAR2(255 CHAR),
    IS_APPROVED VARCHAR2(255 CHAR),
    APPROVAL_DATE TIMESTAMP(6),
    IS_DELETED VARCHAR2(255 CHAR),
    CREATED_BY VARCHAR2(255 CHAR),
    UPDATED_BY VARCHAR2(255 CHAR),
    CREATED_AT TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS EMPLOYERS (
    USER_ID NUMBER(19,0),
    COMPANY_NAME VARCHAR2(255 CHAR),
    WEBSITE VARCHAR2(255 CHAR),
    PHONE_NUM VARCHAR2(255 CHAR),
    COMPANY_IMG_URL VARCHAR2(255 CHAR),
    IS_DELETED VARCHAR2(255 CHAR),
    CREATED_BY VARCHAR2(255 CHAR),
    UPDATED_BY VARCHAR2(255 CHAR),
    CREATED_AT TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS JOB_SEEKERS (
    USER_ID NUMBER(19,0),
    FIRST_NAME VARCHAR2(255 CHAR),
    LAST_NAME VARCHAR2(255 CHAR),
    NATIONAL_ID VARCHAR2(255 CHAR),
    BIRTH_DATE TIMESTAMP(6),
    CV_ID NUMBER(19,0),
    IS_APPROVED VARCHAR2(255 CHAR),
    APPROVAL_DATE TIMESTAMP(6),
    IS_DELETED VARCHAR2(255 CHAR),
    CREATED_BY VARCHAR2(255 CHAR),
    UPDATED_BY VARCHAR2(255 CHAR),
    CREATED_AT TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6)
);
