package com.tolgakumbul.mernis;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 7.5.0.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public interface VDDIServiceEvents
{
    void Starting();
    void Completed(VDDOperationResult result);
}
