package com.tolgakumbul.mernis;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 7.5.0.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public class VDDOperationResult< T>
{
    private java.lang.Exception exception;
    private T result;
    private java.lang.Object tag;
    private java.lang.String methodName;
    
    public java.lang.Exception getException()
    {
        return this.exception;    
    }
    
    public void setException(java.lang.Exception value)
    {
        this.exception=value;
    }
    
    public T getResult()
    {
        return this.result;    
    }
    
    public void setResult(T value)
    {
        this.result=value;
    }
    
    public java.lang.Object getTag()
    {
        return this.tag;    
    }
    
    public void setTag(java.lang.Object value)
    {
        this.tag=value;
    }
    
    public java.lang.String getMethodName()
    {
        return this.methodName;    
    }
    
    public void setMethodName(java.lang.String value)
    {
        this.methodName=value;
    }
}
